### ISSUE TITLE
Information about Express

### ISSUE THREAD

**Issue by dalssoft** [gabrielmellooliveira/herbs2rest#2]
It should be clear on the docs that this glue works with Express (and which version).

```js
const { generateRoutes } = require('herbs2rest')

const routes = new Router()

generateRoutes(controllerList, routes)

app.use(routes)
```

Here, it should be clear that `new Router()` is a express object.

**Comment by gabrielmellooliveira** [comment]
The README has been updated with information to make it clear that herbs2rest works with express.
